name: Auto Cherry Pick

on:
  workflow_dispatch:

jobs:
  cherry-pick:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout local repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch and Cherry-Pick
        run: |
          git remote add spidey https://github.com/spidey-t/android_kernel_oneplus_sm8250.git
          git fetch spidey lineage-23.2
          # 填入你想要提取的 commit 节点
          git cherry-pick 0ab63d9 bd1d761 55b6e67 a2aaaee 648fade 38d5045 9095b3b 39e586f 59580b2
      - name: Push changes
        run: |
          git push origin HEAD
